version: '3.7'

services:
  Wago-Secure-PLC:
    image: 192.168.2.202:5000/secure-pfc:1.0.0
    container_name: "020---wago-secure-pfc"
    command: "/home/alpine/secure-webserver.sh"
    volumes:
      - /root/:/root
    restart: no
