version: '3.7'

services:
  Wago-CAA-Runtime:
    image:  192.168.2.202:5000/caa:1.0.25
    container_name: "050---wago-caa-FW25"
    command: "--init"
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /tmp:/tmp
      - /drm:/drm
    restart: always
