version: '3'

services:
  fw:
    image: 192.168.2.202:5000/fw-update-cc100:04.04.03-26
    restart: on-failure:1
    environment:
      - PASSWORD=wago02
      - SERVICE_NAME=fw
      - MAX_UPDATE_RETRYS=5
      - CERT_NAME=
      - FILEPATH=/etc/docker/
      - FILE=daemon.json
