version: '3.7'
 
services:
  Wago-CAA-Runtime:
    image: 192.168.2.202:5000/tp-ectrl-fw26:latest
    container_name: "051---wago-caa3-tp-ectrl-fw26"
    command: "--init"
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /tmp:/tmp
      - /drm:/drm
    restart: always
