version: '3.7'

services:
  Wago-CAA-Runtime:
    image: 192.168.2.202:5000/app-led-pfc-8212:1.0
    container_name: "102-8212-app-led-FW26"
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /tmp:/tmp
      - /drm:/drm
    command: "--init"
