version: '3.7'

services:
  fw:
    image:  192.168.2.202:5000/fw-update-edge:04.03.03-25
    restart: on-failure:1
    environment:
      - PASSWORD=wago02
      - SERVICE_NAME=fw
      - MAX_UPDATE_RETRYS=5
      - CERT_NAME=
      - FILEPATH=/etc/docker/
      - FILE=daemon.json
