version: '3.7'
 
services:
  Wago-CAA-Runtime:
    image: 192.168.2.202:5000/pfc-fw26:latest
    container_name: "050---wago-caa3-FW26"
    command: "--init"
    network_mode: host
    privileged: true
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /tmp:/tmp
      - /drm:/drm
    restart: always
